# Generated by Django 3.1.5 on 2021-01-09 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210109_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='expire_date',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='job_type',
            field=models.CharField(choices=[('Part Time', 'P'), ('Full Time', 'F'), ('Other', 'O')], max_length=255),
        ),
    ]
