# Generated by Django 3.1.5 on 2021-01-08 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
