# Generated by Django 3.1.5 on 2021-01-11 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210109_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='job_type',
            field=models.CharField(choices=[('Part Time', 'P'), ('Other', 'O'), ('Full Time', 'F')], max_length=255),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='salary',
            field=models.CharField(max_length=100),
        ),
    ]
