# Generated by Django 3.1.5 on 2021-01-08 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_companyowner'),
        ('app', '0003_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.companyowner'),
        ),
        migrations.DeleteModel(
            name='CompanyOwner',
        ),
    ]
