# Generated by Django 3.1.5 on 2021-01-16 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210115_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='job_type',
            field=models.CharField(choices=[('Part Time', 'P'), ('Other', 'O'), ('Full Time', 'F')], max_length=255),
        ),
    ]
