# Generated by Django 3.1.5 on 2021-01-20 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20210120_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='photo',
            field=models.FileField(null=True, upload_to='media/jobs/'),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='job_type',
            field=models.CharField(choices=[('Part Time', 'P'), ('Other', 'O'), ('Full Time', 'F')], max_length=255),
        ),
    ]
