# Generated by Django 3.1.5 on 2021-01-20 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20210120_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='job_type',
            field=models.CharField(choices=[('Part Time', 'P'), ('Full Time', 'F'), ('Other', 'O')], max_length=255),
        ),
    ]
