# Generated by Django 3.1.5 on 2021-01-20 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20210120_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='job_type',
            field=models.CharField(choices=[('Full Time', 'F'), ('Part Time', 'P'), ('Other', 'O')], max_length=255),
        ),
        migrations.AlterField(
            model_name='resume',
            name='photo',
            field=models.FileField(null=True, upload_to='resume/'),
        ),
    ]
