# Generated by Django 3.1.3 on 2021-01-21 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20210121_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='job_type',
            field=models.CharField(choices=[('Full Time', 'F'), ('Other', 'O'), ('Part Time', 'P')], max_length=255),
        ),
    ]
