# Generated by Django 3.1.5 on 2021-01-15 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_education',
            field=models.CharField(default='', max_length=200),
        ),
    ]
