# Generated by Django 3.1.5 on 2021-01-15 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_last_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='graduate_year',
            field=models.CharField(default='', max_length=200),
        ),
    ]
