# Generated by Django 3.1.5 on 2021-01-16 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_profile_job_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='salary_range',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
