# Generated by Django 3.1.5 on 2021-01-20 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_profile_salary_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pro_photo',
            field=models.FileField(null=True, upload_to='media/profile'),
        ),
    ]
