# Generated by Django 3.1.5 on 2021-01-20 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_profile_pro_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyowner',
            name='photo',
            field=models.FileField(null=True, upload_to='media/company/'),
        ),
    ]
