# Generated by Django 3.1.5 on 2021-01-20 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_companyowner_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='resume',
            field=models.FileField(null=True, upload_to='resume/'),
        ),
    ]
