# Generated by Django 3.1.5 on 2021-01-20 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_profile_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pro_photo',
            field=models.FileField(blank=True, null=True, upload_to='media/profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resume/'),
        ),
    ]
