# Generated by Django 3.1.3 on 2021-01-21 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20210121_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyowner',
            name='company_logo',
            field=models.FileField(blank=True, null=True, upload_to='company'),
        ),
        migrations.AlterField(
            model_name='companyowner',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='media/company/'),
        ),
    ]
